# [en]
#   languageName = "English"
#   contentDir = "content/en"
#   weight = 20
#   [en.params]
#     languageISO = "EN"
#     languageTag = "en-US"
#     footer = 'Brought to you by <a class="text-muted" href="https://thulite.io/">Thulite</a>'
#     alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[ja]
  languageName = "日本語"
  contentDir = "content/ja"
  weight = 10
  [ja.params]
    languageISO = "JA"
    languageTag = "ja-JP"
    titleAddition = "TASKMANanger Document"
    description = "Task管理アプリ"
    titleHome = "TASKMANanger"
    footer = '開発運営:<a href="https://sndbox.jp/">合同会社サンドボックス</a>'
    alertText = 'Welcome to TASKMANanger'
